spring:
  application:
    name: springboot-rabbitmq-demo
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
rabbitmq:
  queue:
    name: spring-boot-queue
    json:
      name: json-queue
  exchange:
    name: spring-boot-exchange
  routing:
    key: spring-boot-routing-key
    json:
      key: json-routing-key
